version: '3.8'

services:
  test_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: test_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"